# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Augmented Kalman filter
#' 
#' Implementation of the augmented Kalman filter for the special
#' case of the current model. The augmented Kalman filter is a
#' modified version of the standard Kalman filter that
#' considers the the error terms' correlation and the constant
#' \eqn{\mu} in the state equation.
#' Used to calculate the likelihood of \eqn{\theta=(\phi,\sigma,\rho)},
#' and to calculate the posterior of \eqn{\mu}.
#' For a specification see Appendix B of Nakajima, 2009.
#' @author hdarjus \email{hdarjus@gmail.com}
#' @param dPhi parameter \eqn{\phi}
#' @param dSigma2 square of parameter \eqn{\sigma}
#' @param dRho parameter \eqn{\rho}
#' @param va numeric vector of mixture states constants
#' @param vb numeric vector of mixture states constants
#' @param vm numeric vector of mixture states constants
#' @param vv numeric vector of mixture states constants
#' @param vD vector of signs
#' @param vYStar vector of y*
#' @param dMuMu prior mean of \eqn{\mu}
#' @param dSigma2Mu prior variance of \eqn{\mu}
#' @return List with elements \code{D, J1, L, f, F, hts, v, Q, q, jt22, h1var}, from which
#'   \code{D, J1, L, f, F, h1var, v} are numeric vectors of length T,
#'   and \code{Q, q, jt22, h1var} are numbers. All of them are just partial results helping
#'   later calculations.
#' @references Nakajima, Jouchi, and Yasuhiro Omori.
#'   "Leverage, heavy-tails and correlated jumps in stochastic volatility models."
#'   Computational Statistics & Data Analysis 53.6 (2009): 2335-2353.
fnAugKalmanFilterCpp <- function(phi, sigma2, rho, a, b, m, v, d, y_star, mu_mu, sigma2_mu, centering) {
    .Call('_stochvollev_fnAugKalmanFilterCpp', PACKAGE = 'stochvollev', phi, sigma2, rho, a, b, m, v, d, y_star, mu_mu, sigma2_mu, centering)
}

