#ifdef COMPILE_STOCHOL_CPP_TESTS
/*
 * Please do not edit this file -- it ensures that your package will export a
 * 'run_testthat_tests()' C routine that can be used to run the Catch unit tests
 * available in your package.
 */
#define TESTTHAT_TEST_RUNNER
#include <testthat.h>
#else
#include <Rcpp.h>
RcppExport SEXP run_testthat_tests () {
  return Rcpp::wrap(Rcpp::LogicalVector::create(true));
}
#endif

