# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Augmented Kalman filter
#' 
#' Implementation of the augmented Kalman filter for the special
#' case of the current model. The augmented Kalman filter is a
#' modified version of the standard Kalman filter that
#' considers the the error terms' correlation and the constant
#' \eqn{\mu} in the state equation.
#' Used to calculate the likelihood of \eqn{\theta=(\phi,\sigma,\rho)},
#' and to calculate the posterior of \eqn{\mu}.
#' For a specification see Appendix B of Nakajima, 2009.
#' @author hdarjus \email{hdarjus@gmail.com}
#' @param dPhi parameter \eqn{\phi}
#' @param dSigma2 square of parameter \eqn{\sigma}
#' @param dRho parameter \eqn{\rho}
#' @param va numeric vector of mixture states constants
#' @param vb numeric vector of mixture states constants
#' @param vm numeric vector of mixture states constants
#' @param vv numeric vector of mixture states constants
#' @param vD vector of signs
#' @param vYStar vector of y*
#' @param dMuMu prior mean of \eqn{\mu}
#' @param dSigma2Mu prior variance of \eqn{\mu}
#' @return List with elements \code{D, J1, L, f, F, hts, v, Q, q, jt22, h1var}, from which
#'   \code{D, J1, L, f, F, h1var, v} are numeric vectors of length T,
#'   and \code{Q, q, jt22, h1var} are numbers. All of them are just partial results helping
#'   later calculations.
#' @references Nakajima, Jouchi, and Yasuhiro Omori.
#'   "Leverage, heavy-tails and correlated jumps in stochastic volatility models."
#'   Computational Statistics & Data Analysis 53.6 (2009): 2335-2353.
aug_kalman_filter <- function(phi, rho, sigma2, a, b, m, v, d, y_star, mu_mu, sigma2_mu, centering) {
    .Call(`_stochvol_aug_kalman_filter`, phi, rho, sigma2, a, b, m, v, d, y_star, mu_mu, sigma2_mu, centering)
}

draw_h_auxiliary <- function(y_star, d, s, phi, rho, sigma2, mu, centering, mixing_constants) {
    .Call(`_stochvol_draw_h_auxiliary`, y_star, d, s, phi, rho, sigma2, mu, centering, mixing_constants)
}

draw_latent_auxiliaryMH <- function(y, y_star, d, h, phi, rho, sigma2, mu, mixing_constants) {
    .Call(`_stochvol_draw_latent_auxiliaryMH`, y, y_star, d, h, phi, rho, sigma2, mu, mixing_constants)
}

draw_s_auxiliary <- function(y_star, d, h, phi, rho, sigma2, mu, centering, mixing_constants) {
    .Call(`_stochvol_draw_s_auxiliary`, y_star, d, h, phi, rho, sigma2, mu, centering, mixing_constants)
}

mixture_state_post_dist <- function(eps_star, eta, d, mu, sigma2, rho, centering, mixing_constants) {
    .Call(`_stochvol_mixture_state_post_dist`, eps_star, eta, d, mu, sigma2, rho, centering, mixing_constants)
}

svlsample_cpp <- function(n, y, y_star, d, thin, burnin, phi_init, rho_init, sigma2_init, mu_init, h_init, prior_phi_a, prior_phi_b, prior_rho_a, prior_rho_b, prior_sigma2_shape, prior_sigma2_rate, prior_mu_mu, prior_mu_sigma2, stdev, strategy, mixing_constants) {
    .Call(`_stochvol_svlsample_cpp`, n, y, y_star, d, thin, burnin, phi_init, rho_init, sigma2_init, mu_init, h_init, prior_phi_a, prior_phi_b, prior_rho_a, prior_rho_b, prior_sigma2_shape, prior_sigma2_rate, prior_mu_mu, prior_mu_sigma2, stdev, strategy, mixing_constants)
}

simulation_smoother <- function(mu, filter_results, centering) {
    .Call(`_stochvol_simulation_smoother`, mu, filter_results, centering)
}

draw_theta_rwMH <- function(phi, rho, sigma2, mu, y, h, prior_phi, prior_rho, prior_sigma2, prior_mu, centering, stdev = .1) {
    .Call(`_stochvol_draw_theta_rwMH`, phi, rho, sigma2, mu, y, h, prior_phi, prior_rho, prior_sigma2, prior_mu, centering, stdev)
}

draw_theta_auxiliary <- function(phi, rho, sigma2, mu, y_star, d, s, prior_phi, prior_rho, prior_sigma2, prior_mu, mixing_constants) {
    .Call(`_stochvol_draw_theta_auxiliary`, phi, rho, sigma2, mu, y_star, d, s, prior_phi, prior_rho, prior_sigma2, prior_mu, mixing_constants)
}

theta_log_likelihood <- function(phi, rho, sigma2, mu, y, h, centering) {
    .Call(`_stochvol_theta_log_likelihood`, phi, rho, sigma2, mu, y, h, centering)
}

theta_log_prior <- function(phi, rho, sigma2, mu, prior_phi, prior_rho, prior_sigma2, prior_mu) {
    .Call(`_stochvol_theta_log_prior`, phi, rho, sigma2, mu, prior_phi, prior_rho, prior_sigma2, prior_mu)
}

theta_transform <- function(f, r, s, m) {
    .Call(`_stochvol_theta_transform`, f, r, s, m)
}

theta_transform_inv <- function(phi, rho, sigma2, mu) {
    .Call(`_stochvol_theta_transform_inv`, phi, rho, sigma2, mu)
}

theta_transform_log_det_jac <- function(f, r, s, m) {
    .Call(`_stochvol_theta_transform_log_det_jac`, f, r, s, m)
}

theta_transform_inv_log_det_jac <- function(phi, rho, sigma2, mu) {
    .Call(`_stochvol_theta_transform_inv_log_det_jac`, phi, rho, sigma2, mu)
}

theta_proposal_stdev <- function(phi, rho, sigma2, mu, y, h, stdev = .1) {
    .Call(`_stochvol_theta_proposal_stdev`, phi, rho, sigma2, mu, y, h, stdev)
}

theta_propose <- function(phi, rho, sigma2, mu, y, h, stdev = .1) {
    .Call(`_stochvol_theta_propose`, phi, rho, sigma2, mu, y, h, stdev)
}

auxtheta_log_posterior <- function(auxtheta, a, b, mm, v, d, y_star, prior_phi, prior_rho, prior_sigma2, prior_mu) {
    .Call(`_stochvol_auxtheta_log_posterior`, auxtheta, a, b, mm, v, d, y_star, prior_phi, prior_rho, prior_sigma2, prior_mu)
}

