# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampler <- function(y_in, draws_in, burnin_in, X_in, bmu_in, Bmu_in, a0_in, b0_in, Bsigma_in, thin_in, timethin_in, startpara_in, startvol_in, keeptau_in, quiet_in, para_in, MHsteps_in, B011_in, B022_in, mhcontrol_in, gammaprior_in, truncnormal_in, offset_in, dontupdatemu_in, priordf_in, priorbeta_in, priorlatent0_in) {
    .Call(`_stochvol_sampler`, y_in, draws_in, burnin_in, X_in, bmu_in, Bmu_in, a0_in, b0_in, Bsigma_in, thin_in, timethin_in, startpara_in, startvol_in, keeptau_in, quiet_in, para_in, MHsteps_in, B011_in, B022_in, mhcontrol_in, gammaprior_in, truncnormal_in, offset_in, dontupdatemu_in, priordf_in, priorbeta_in, priorlatent0_in)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_stochvol_RcppExport_registerCCallable', PACKAGE = 'stochvol')
})
