// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fnAugKalmanFilterCpp
List fnAugKalmanFilterCpp(const double phi, const double sigma2, const double rho, const NumericVector a, const NumericVector b, const NumericVector m, const NumericVector v, const NumericVector d, const NumericVector y_star, const double mu_mu, const double sigma2_mu, const StringVector centering);
RcppExport SEXP _stochvollev_fnAugKalmanFilterCpp(SEXP phiSEXP, SEXP sigma2SEXP, SEXP rhoSEXP, SEXP aSEXP, SEXP bSEXP, SEXP mSEXP, SEXP vSEXP, SEXP dSEXP, SEXP y_starSEXP, SEXP mu_muSEXP, SEXP sigma2_muSEXP, SEXP centeringSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< const double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type y_star(y_starSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_mu(mu_muSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma2_mu(sigma2_muSEXP);
    Rcpp::traits::input_parameter< const StringVector >::type centering(centeringSEXP);
    rcpp_result_gen = Rcpp::wrap(fnAugKalmanFilterCpp(phi, sigma2, rho, a, b, m, v, d, y_star, mu_mu, sigma2_mu, centering));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stochvollev_fnAugKalmanFilterCpp", (DL_FUNC) &_stochvollev_fnAugKalmanFilterCpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_stochvollev(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
